baseurl                  = "https://gifted-kirch-bfc8d4.netlify.app/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Call me Amrit"
theme = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "amrit.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Amrit Patel's photography portfolio." # Max 160 characters show in search results
    images               = ["amrit.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Amrit Patel's photography portfolio."
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "projects"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "about"
    text = "about"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
    resampleFilter = "box"

# Default JPEG quality setting. Default is 75.
    quality = 75
